Suji/lost found write screen
ahachulTeam/ahachul_app pull request #4
Opened 2023-05-21 16:28 UTC by suji8073

## 분실물, 습득물 작성하는 화면 코드 리뷰 부탁드립니다
* 아직 제작 중에 있습니다 ㅠㅠ

* 사진 관련 로직은 아직 추가 전입니다. 디자인 측면에서 문의 사항이 있어 보류 중입니다.
* 호선을 선택하는 바텀 시트는 FlatList로 제작 예정입니다.
* 작성 폼 textInput, textArea 컴포넌트는 다른 곳에서도 사용될 것 같아 common 부분에 제작해놓았습니다.

2023-05-24 11:57 UTC, hoonjoo-park requested changes

2023-05-24 11:57 UTC, hoonjoo-park commented on components/LostFound/ItemRow.tsx
> +}) => {
props들 다 interface로 빼주시길 바랍니다!
그리고 [key: string]: any 보다는, 아직 데이터 반환 형식이 어떻게 될지는 몰라도 
MockData에 대한 타입 인터페이스 만들어서 활용하시는 것 제안 드리고싶습니다.

저도 MockData라고 할지라도, 그냥 제가 생각하는 키-쌍을 구상해서 타입을 선언해서 썼었거든요..!

2023-05-24 11:57 UTC, hoonjoo-park commented on components/LostFound/ItemRow.tsx
> +    </Container>
style 객체는 한 줄 뿐이더라도 styled 사용해주세요~

2023-05-24 11:57 UTC, hoonjoo-park commented on components/LostFound/ItemRow.tsx
> +  )
사실 빈 TouchableOpacity가 필요한 이유가 뭔지 잘 모르겠습니다ㅜ 

비어있는 UI에 대한 레이아웃이 필요한거면 View를 사용하는것이 맞다고 보며, 
그게 아니라면 fragment(<></>)를 사용하는 것 제안 드리고 싶습니다.

2023-05-24 11:57 UTC, hoonjoo-park commented on components/LostFound/WriteInput.tsx
> +}
객체 확장성을 고려해, Props 등은 웬만하면 interface를 사용해주세요.

그리고 추가적으로, `mb`는 style에 포섭될 수 있는 하위 타입이라고 생각되는데, 굳이 style과 mb를 나눠서 전달해주는 이유가 궁금합니다. 사실 스타일 프로퍼티를 props로 하나하나 직접 내려주는게 좋은 패턴은 아니라고 생각해요ㅜ (containerStyle, inputStyle로 나눠서 받는게 좋지 않을까요?)

마지막으로, 본 컴포넌트가 어디서 사용되는지 모르겠습니다. 현재 PR에는 해당 컴포넌트를 사용하는 파일이 없는 것 같아서요!

따라서 해당 컴포넌트에 대한 리뷰는 추후 추가적으로 진행하도록 하겠습니다.

2023-05-24 11:57 UTC, hoonjoo-park commented on components/bottom-sheet/SelectLineBottomSheet.tsx
> +  })
select에 대한 타입 지정 부탁드립니다!

2023-05-24 11:57 UTC, hoonjoo-park commented on components/bottom-sheet/SelectLineBottomSheet.tsx
> +  ]
상수는 컴포넌트 밖에 선언해주시길 바랍니다.
컴포넌트의 리렌더링과 관계 없이 변하지 않기 때문에, 컴포넌트 밖에 선언하는 것이 더 효율적이기 때문입니다.

2023-05-24 11:57 UTC, hoonjoo-park commented on components/bottom-sheet/SelectLineBottomSheet.tsx
> +  })
그리고 추가적으로, select라는 모호한 변수명보다는, 좀 더 길어지더라도 명확한 selectedSubwayLine 등이 더 좋은 네이밍 방식이라고 생각해요

2023-05-24 11:57 UTC, hoonjoo-park commented on components/bottom-sheet/SelectLineBottomSheet.tsx
> +            />
사실 FlatList 사용이 굳이 필요한지 의문입니다. 
캐싱이나 지연 렌더링 등이 필요 없는 부분인데다가, 데이터의 양도 많지 않고, flex-wrap 등으로 충분히 column 스타일을 구현할 수 있다고 봐서요. 심지어 ReactNative 0.7버전부터는 gap 사용이 가능해서 어렵지 않으리라 봅니다.

첨언하자면, 개인적으로 FlatList는 대량의 리스트를 반복 렌더링 해야되거나, 렌더링해야 되는 부수 컴포넌트에 이미지 등이 있는 복잡한 구조일 때 사용하는게 좋다고 생각해요.

2023-05-24 11:57 UTC, hoonjoo-park commented on components/bottom-sheet/SelectLineBottomSheet.tsx
> +      </Indicator>
당장은 아니더라도, 추후 Reanimated로 interpolation 등을 활용해서 페이지네이션 구현 필요할 것 같습니다.

이 부분은 제가 onboarding 등의 스크린에 비슷한 패턴 구현해놓도록 하겠습니다.

2023-05-26 01:07 UTC, suji8073 commented on components/LostFound/WriteInput.tsx
> +}
네, 반영해서 PR 올렸습니다! 해당 컴포넌트는 LostFoundWriteScreen에서 사용되고 있습니다!

2023-05-26 01:08 UTC, suji8073 commented
@hoonjoo-park 달아주신 코멘트 반영하여 코드 수정하였습니다! 확인 부탁드립니다 !!

2023-08-02 05:42 UTC, merged