refactor: 게시물 상세보기 이동하기 위해 게시물 리스트 touchable opacity로 변경
ahachulTeam/ahachul_app pull request #5
Opened 2023-05-25 02:56 UTC by seilylook

구현 사항
* View style 분리했습니다.
* 클릭시 유실물 상세보기 페이지로 이동하기 위해 LostPost를 TouchableOpacity로 변경했습니다.

2023-05-25 15:51 UTC, createhb21 commented
merge는 한 개 이상의 리뷰 및 approve가 있으면 하는 게 좋을 것 같아요 !

2023-05-26 16:08 UTC, hoonjoo-park requested changes

2023-05-26 16:08 UTC, hoonjoo-park commented on screens/LostFound/LostPost.tsx
>    margin-left: 10px;
수지님이 만드신 공통 컴포넌트인 CSButton을 사용해주세요~

2023-05-26 16:08 UTC, hoonjoo-park commented on screens/LostFound/LostPostList.tsx
>        renderItem={renderItem}
keyExtractor 사용해주세요!

2023-05-26 16:08 UTC, hoonjoo-park commented on screens/LostFound/LostDetail.tsx
> +  height: 24;
styled는 반드시 뒤에 px과 같은 단위를 붙여줘야 합니다. 따라서 24px과 같이 값 단위를 붙여주세요~

2023-05-26 16:08 UTC, hoonjoo-park commented on App/stacks/MainStack.tsx
이건 제가 만든 컴포넌트인가요? 

일단 세현님 이 브랜치는 이전에 직접 merge 하신 부분을 revert 후에 다시 브랜치들을 정리 하고, 다시 리뷰 후에 merge 하는 것이 좋을 것 같습니다.

일단 눈에 바로 보이는 것들만 리뷰 해드릴게요!

2023-06-03 05:57 UTC, seilylook commented on App/stacks/MainStack.tsx
네비게이션 작동하는지 시도하느라 임시로 만든거 입니다!

2023-06-03 06:03 UTC, seilylook commented
제가 현대오토에버 면접이 잡혀서 코드 수정이 늦었습니다. 죄송합니다. 
최대한 빨리 반영하겠습니다.

revert는 시도해서 main에 merge된 코드들이 사라지긴 했는데 이런식으로 하는 게 맞는지는 모르겠습니다.

2023-06-03 07:02 UTC, seilylook commented
수정
* LostPost 컴포넌트 CSButton으로 변경
* LostPostList 컴포넌트 keyExtractor 반영

LostDetail 컴포넌트는 유실물 리스트에서 클릭했을 때 navigation 작동하는지 시험해보려 만든 컴포넌트입니다. 
추후에 각 작업들 merge되면 바꾸겠습니다!

2023-06-29 03:21 UTC, hoonjoo-park approved these changes

2023-08-26 10:56 UTC, merged